### ISSUE TITLE
User Module | Delete User Feature

### ISSUE THREAD

**Issue by kishor-repo** [fssa-batch3/sec_a_kishor.muruganandham__corejava_project_2#22]
# User Delete Process

### User Story
As a user, I would like the ability to deactivate my account in the application. By deactivating my account, I ensure that my  personal information is no longer accessible or displayed.

### Task

- [x] Implement Data Access Object (DAO) Layer.
- [x] Implement Service Layer.
- [x] Create JUnit Test Cases.
- [x] Ensure that the tests cases are passing.
- [x] Write clear and concise comments in the code to explain complex logic.

#### DAO
- deleteUser()

#### Service
- deleteUser()

#### Junit Test
- testValidDeleteUser()
- testInvalidDeleteUser()

### Estimation
- 2 hours

# Flowchart

```mermaid
graph TD
A[[Start]] --> B([User Initiates Account Delete])
B --> C([Check If User Exists and Active])
C --> |User Not Found or Inactive|H([Validation Exception])
C --> |Display Delete Confirmation| D([User Confirms Delete])
D --> |User Confirms| E[(Delete Account)]
E --> |Return true| F[User Deleted Successfully]
E --> |Fail| G[Failed to Delete User]
H --> G
F --> I[[End]]
G --> I

style F fill:#dfd,stroke:#333
style G fill:#fdd,stroke:#333
