### ISSUE TITLE
Documentation of README

### ISSUE THREAD

**Issue by Kishor-550** [fssa-batch3/sec_a_kishor.muruganandham__corejava_project_2#8]
# Documentation of README Process

## Description:
This issue involves documenting the README file for the project. The README will provide essential information about the project setup, software requirements, modules, validations, testing, and future improvements.

## Tasks :
- [x] Introduction
- [x] Purpose
- [x] Features
- [x] User Persona
- [x] JavaDoc
- [x] Prerequisites
- [x] Software Requirements
- [x] Database Setup
- [x] Project Setup
- [x] Java Project Creation
- [x] Library Dependencies
- [x] Database
- [x] Entity-Relationship Diagram (ERD)
- [x] Database Tables
- [x] Modules
  - [x] User Module
  - [x] Book Module
  - [x] Borrow Module
- [x] Validations
- [x] User Validations
- [x] Book Validations
- [x] Borrow Validations
- [x] Testing
- [x] Unit Testing
- [x] Exception Handling
- [x] Common Error Messages
- [x] Future Improvements
- [x] Planned Features
- [x] Roadmap
- [x] Resources
- [x] External Libraries
- [x] References

**Comment by Kishor-550** [comment]
Done
